version: '3'

networks:
  hk-monitoring:
    driver: bridge
  
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - hk-monitoring

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - hk-monitoring
  mysql_exporter:
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    ports:
      - "9101:9101"
    networks:
      - hk-monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    #depends_on:
    #  - prometheus
    ports:
      - "3000:3000"
    networks:
      - hk-monitoring
