global:
  scrape_interval: 5s
  external_labels:
    monitor: 'hk-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
   
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql_exporter:9101']
